CREATE TABLE players (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  player TEXT NOT NULL,
  team TEXT NOT NULL,
  fantasy_position TEXT NOT NULL,
  age INTEGER NOT NULL,
  games INTEGER NOT NULL,
  games_started INTEGER NOT NULL,
  completions INTEGER,
  pass_attempts INTEGER,
  pass_yards INTEGER,
  pass_tds INTEGER,
  interceptions INTEGER,
  rush_attempts INTEGER,
  rush_yards INTEGER,
  rush_yards_per_attempt REAL,
  rush_tds INTEGER,
  targets INTEGER,
  receptions INTEGER,
  rec_yards INTEGER,
  yards_per_reception REAL,
  rec_tds INTEGER,
  fumbles INTEGER,
  fumbles_lost INTEGER,
  total_tds INTEGER,
  two_point_con INTEGER,
  two_point_con_passing INTEGER,
  fantasy_points_standard INTEGER,
  fantasy_points_ppr REAL,
  dk_fantasy_points REAL,
  fd_fantasy_points REAL
);
